Repository Kong/kubernetes-configuration, pull requests merged in 2025-06, with the labels that each got.

#447 chore: remove duplicated doc comments
  api/common/v1alpha1/doc.go
  api/gateway-operator/v1alpha1/groupversion_info.go
  api/gateway-operator/v1beta1/groupversion_info.go
  docs/all-api-reference.md
  docs/gateway-operator-api-reference.md
Labels: area/docs

#456 chore: do not mark `DataPlaneMetricsExtension` as EE only
  CHANGELOG.md
  api/gateway-operator/v1alpha1/dataplane_metrics_extension_types.go
  config/crd/gateway-operator/gateway-operator.konghq.com_dataplanemetricsextensions.yaml
  docs/all-api-reference.md
  docs/gateway-operator-api-reference.md
Labels: documentation, area/debt

#461 ci: enable optionalorrequired in kube-api-linter
  .golangci-kube-api.yaml
  api/common/v1alpha1/controlplaneref_types.go
  api/common/v1alpha1/extensionref_types.go
  api/common/v1alpha1/kongobject_ref.go
  api/configuration/v1/kongclusterplugin_types.go
  api/configuration/v1/kongplugin_types.go
  api/configuration/v1alpha1/kong_ca_certificate.go
  api/configuration/v1alpha1/kong_certificate.go
  api/configuration/v1alpha1/kongcredential_acl_types.go
  api/configuration/v1alpha1/kongcredential_apikey_types.go
  api/configuration/v1alpha1/kongcredential_basic_auth_types.go
  api/configuration/v1alpha1/kongcredential_hmac_types.go
  api/configuration/v1alpha1/kongcredential_jwt_types.go
  api/configuration/v1alpha1/kongdataplaneclientcertificate_types.go
  api/configuration/v1alpha1/kongkeyset_types.go
  api/configuration/v1alpha1/kongpluginbinding_types.go
  api/configuration/v1alpha1/kongservice_types.go
  api/configuration/v1alpha1/kongupstream_types.go
  api/configuration/v1beta1/ingress_rules.go
  api/gateway-operator/v1alpha1/aigateway_cloud_providers.go
  api/gateway-operator/v1alpha1/aigateway_endpoints.go
  api/gateway-operator/v1alpha1/aigateway_llm_prompts.go
  api/gateway-operator/v1alpha1/aigateway_types.go
  api/gateway-operator/v1alpha1/dataplane_metrics_extension_types.go
  api/gateway-operator/v1alpha1/kongplugin_installation_types.go
  api/gateway-operator/v1alpha1/watchnamespacegrant_types.go
  api/gateway-operator/v1beta1/shared_types.go
  api/gateway-operator/v2alpha1/controlplane_types.go
  api/incubator/v1alpha1/kongservicefacade_types.go
  api/konnect/v1alpha1/konnect_apiauthconfiguration_types.go
  api/konnect/v1alpha1/konnect_cloudgateway_dataplane_configuration_types.go
  api/konnect/v1alpha1/konnect_cloudgateway_network_types.go
  api/konnect/v1alpha1/konnect_cloudgateway_transitgateway_types.go
  api/konnect/v1alpha1/konnect_configuration.go
  api/konnect/v1alpha1/konnect_entity_status.go
  api/konnect/v1alpha1/konnect_gateway_controlplane_types.go
  api/konnect/v1alpha2/konnect_extension_types.go
  config/crd/gateway-operator/gateway-operator.konghq.com_controlplanes.yaml
  config/crd/gateway-operator/konnect.konghq.com_konnectgatewaycontrolplanes.yaml
  docs/all-api-reference.md
  docs/gateway-operator-api-reference.md
  docs/konnect-api-reference.md
Labels: area/ci

#463 feat: add sticky-session support for KongUpstreamPolicy
  CHANGELOG.md
  api/configuration/v1beta1/kongupstreampolicy_types.go
  api/configuration/v1beta1/zz_generated.deepcopy.go
  config/crd/ingress-controller/configuration.konghq.com_kongupstreampolicies.yaml
  docs/all-api-reference.md
  docs/configuration-api-reference.md
  test/crdsvalidation/configuration.konghq.com/kongupstreampolicy_test.go
Labels: release/required
