Repository Kong/kubernetes-configuration, pull requests merged in 2025-03, with the labels that each got.

#343 fix(konnect): fix KonnectGatewayControlPlane CEL rules checking `cloud_gateway` field
  api/konnect/v1alpha1/konnect_gateway_controlplane_types.go
  config/crd/gateway-operator/konnect.konghq.com_konnectgatewaycontrolplanes.yaml
  test/crdsvalidation/konnect.konghq.com/konnectgatewaycontrolplane_test.go
Labels: area/konnect

#342 feat: add ready column to KonnectExtension
  api/konnect/v1alpha1/konnect_extension_types.go
  config/crd/gateway-operator/konnect.konghq.com_konnectextensions.yaml
Labels: release/required

#355 chore: add KGO CRD install instructions
  README.md
Labels: documentation
