Repository Kong/kubernetes-configuration, pull requests merged in 2025-01, with the labels that each got.

#203 feat: add version information to CRDs
  .github/workflows/release.yaml
  .github/workflows/release_on_version_change.yaml
  Makefile
  README.md
  VERSION
  config/crd/gateway-operator/configuration.konghq.com_kongcacertificates.yaml
  config/crd/gateway-operator/configuration.konghq.com_kongcertificates.yaml
  config/crd/gateway-operator/configuration.konghq.com_kongconsumergroups.yaml
  config/crd/gateway-operator/configuration.konghq.com_kongconsumers.yaml
  config/crd/gateway-operator/configuration.konghq.com_kongcredentialacls.yaml
  config/crd/gateway-operator/configuration.konghq.com_kongcredentialapikeys.yaml
  config/crd/gateway-operator/configuration.konghq.com_kongcredentialbasicauths.yaml
  config/crd/gateway-operator/configuration.konghq.com_kongcredentialhmacs.yaml
  config/crd/gateway-operator/configuration.konghq.com_kongcredentialjwts.yaml
  config/crd/gateway-operator/configuration.konghq.com_kongdataplaneclientcertificates.yaml
  config/crd/gateway-operator/configuration.konghq.com_kongkeys.yaml
  config/crd/gateway-operator/configuration.konghq.com_kongkeysets.yaml
  config/crd/gateway-operator/configuration.konghq.com_konglicenses.yaml
  config/crd/gateway-operator/configuration.konghq.com_kongpluginbindings.yaml
  config/crd/gateway-operator/configuration.konghq.com_kongplugins.yaml
  config/crd/gateway-operator/configuration.konghq.com_kongroutes.yaml
  config/crd/gateway-operator/configuration.konghq.com_kongservices.yaml
  config/crd/gateway-operator/configuration.konghq.com_kongsnis.yaml
  config/crd/gateway-operator/configuration.konghq.com_kongtargets.yaml
  config/crd/gateway-operator/configuration.konghq.com_kongupstreams.yaml
  config/crd/gateway-operator/configuration.konghq.com_kongvaults.yaml
  config/crd/gateway-operator/konnect.konghq.com_konnectapiauthconfigurations.yaml
  config/crd/gateway-operator/konnect.konghq.com_konnectgatewaycontrolplanes.yaml
  config/crd/ingress-controller-incubator/incubator.ingress-controller.konghq.com_kongservicefacades.yaml
  config/crd/ingress-controller/configuration.konghq.com_ingressclassparameterses.yaml
  config/crd/ingress-controller/configuration.konghq.com_kongclusterplugins.yaml
  config/crd/ingress-controller/configuration.konghq.com_kongconsumergroups.yaml
  config/crd/ingress-controller/configuration.konghq.com_kongconsumers.yaml
  config/crd/ingress-controller/configuration.konghq.com_kongcustomentities.yaml
  config/crd/ingress-controller/configuration.konghq.com_kongingresses.yaml
  config/crd/ingress-controller/configuration.konghq.com_konglicenses.yaml
  config/crd/ingress-controller/configuration.konghq.com_kongplugins.yaml
  config/crd/ingress-controller/configuration.konghq.com_kongupstreampolicies.yaml
  config/crd/ingress-controller/configuration.konghq.com_kongvaults.yaml
  config/crd/ingress-controller/configuration.konghq.com_tcpingresses.yaml
  config/crd/ingress-controller/configuration.konghq.com_udpingresses.yaml
  scripts/crds-generator/main.go
Labels: area/ci

#208 chore(ci): fix release on version change workflow
  .github/workflows/release_on_version_change.yaml
  VERSION
  config/crd/gateway-operator/configuration.konghq.com_kongcacertificates.yaml
  config/crd/gateway-operator/configuration.konghq.com_kongcertificates.yaml
  config/crd/gateway-operator/configuration.konghq.com_kongconsumergroups.yaml
  config/crd/gateway-operator/configuration.konghq.com_kongconsumers.yaml
  config/crd/gateway-operator/configuration.konghq.com_kongcredentialacls.yaml
  config/crd/gateway-operator/configuration.konghq.com_kongcredentialapikeys.yaml
  config/crd/gateway-operator/configuration.konghq.com_kongcredentialbasicauths.yaml
  config/crd/gateway-operator/configuration.konghq.com_kongcredentialhmacs.yaml
  config/crd/gateway-operator/configuration.konghq.com_kongcredentialjwts.yaml
  config/crd/gateway-operator/configuration.konghq.com_kongdataplaneclientcertificates.yaml
  config/crd/gateway-operator/configuration.konghq.com_kongkeys.yaml
  config/crd/gateway-operator/configuration.konghq.com_kongkeysets.yaml
  config/crd/gateway-operator/configuration.konghq.com_konglicenses.yaml
  config/crd/gateway-operator/configuration.konghq.com_kongpluginbindings.yaml
  config/crd/gateway-operator/configuration.konghq.com_kongplugins.yaml
  config/crd/gateway-operator/configuration.konghq.com_kongroutes.yaml
  config/crd/gateway-operator/configuration.konghq.com_kongservices.yaml
  config/crd/gateway-operator/configuration.konghq.com_kongsnis.yaml
  config/crd/gateway-operator/configuration.konghq.com_kongtargets.yaml
  config/crd/gateway-operator/configuration.konghq.com_kongupstreams.yaml
  config/crd/gateway-operator/configuration.konghq.com_kongvaults.yaml
  config/crd/gateway-operator/konnect.konghq.com_konnectapiauthconfigurations.yaml
  config/crd/gateway-operator/konnect.konghq.com_konnectgatewaycontrolplanes.yaml
  config/crd/ingress-controller-incubator/incubator.ingress-controller.konghq.com_kongservicefacades.yaml
  config/crd/ingress-controller/configuration.konghq.com_ingressclassparameterses.yaml
  config/crd/ingress-controller/configuration.konghq.com_kongclusterplugins.yaml
  config/crd/ingress-controller/configuration.konghq.com_kongconsumergroups.yaml
  config/crd/ingress-controller/configuration.konghq.com_kongconsumers.yaml
  config/crd/ingress-controller/configuration.konghq.com_kongcustomentities.yaml
  config/crd/ingress-controller/configuration.konghq.com_kongingresses.yaml
  config/crd/ingress-controller/configuration.konghq.com_konglicenses.yaml
  config/crd/ingress-controller/configuration.konghq.com_kongplugins.yaml
  config/crd/ingress-controller/configuration.konghq.com_kongupstreampolicies.yaml
  config/crd/ingress-controller/configuration.konghq.com_kongvaults.yaml
  config/crd/ingress-controller/configuration.konghq.com_tcpingresses.yaml
  config/crd/ingress-controller/configuration.konghq.com_udpingresses.yaml
Labels: area/ci

#210 chore(ci): fix release on version change workflow
  .github/workflows/release.yaml
  .github/workflows/tests.yaml
Labels: area/ci

#211 Chore(ci): pin 3rd party actions by hashes
  .github/workflows/release.yaml
  .github/workflows/release_on_version_change.yaml
  .github/workflows/tests.yaml
Labels: area/ci

#230 feat: implement Stringer for ControlPlaneRef
  CHANGELOG.md
  VERSION
  api/configuration/v1alpha1/controlplaneref_funcs.go
  api/configuration/v1alpha1/controlplaneref_types.go
  api/configuration/v1alpha1/controlplaneref_types_test.go
  config/crd/gateway-operator/configuration.konghq.com_kongcacertificates.yaml
  config/crd/gateway-operator/configuration.konghq.com_kongcertificates.yaml
  config/crd/gateway-operator/configuration.konghq.com_kongconsumergroups.yaml
  config/crd/gateway-operator/configuration.konghq.com_kongconsumers.yaml
  config/crd/gateway-operator/configuration.konghq.com_kongcredentialacls.yaml
  config/crd/gateway-operator/configuration.konghq.com_kongcredentialapikeys.yaml
  config/crd/gateway-operator/configuration.konghq.com_kongcredentialbasicauths.yaml
  config/crd/gateway-operator/configuration.konghq.com_kongcredentialhmacs.yaml
  config/crd/gateway-operator/configuration.konghq.com_kongcredentialjwts.yaml
  config/crd/gateway-operator/configuration.konghq.com_kongdataplaneclientcertificates.yaml
  config/crd/gateway-operator/configuration.konghq.com_kongkeys.yaml
  config/crd/gateway-operator/configuration.konghq.com_kongkeysets.yaml
  config/crd/gateway-operator/configuration.konghq.com_konglicenses.yaml
  config/crd/gateway-operator/configuration.konghq.com_kongpluginbindings.yaml
  config/crd/gateway-operator/configuration.konghq.com_kongplugins.yaml
  config/crd/gateway-operator/configuration.konghq.com_kongroutes.yaml
  config/crd/gateway-operator/configuration.konghq.com_kongservices.yaml
  config/crd/gateway-operator/configuration.konghq.com_kongsnis.yaml
  config/crd/gateway-operator/configuration.konghq.com_kongtargets.yaml
  config/crd/gateway-operator/configuration.konghq.com_kongupstreams.yaml
  config/crd/gateway-operator/configuration.konghq.com_kongvaults.yaml
  config/crd/gateway-operator/konnect.konghq.com_konnectapiauthconfigurations.yaml
  config/crd/gateway-operator/konnect.konghq.com_konnectgatewaycontrolplanes.yaml
  config/crd/ingress-controller-incubator/incubator.ingress-controller.konghq.com_kongservicefacades.yaml
  config/crd/ingress-controller/configuration.konghq.com_ingressclassparameterses.yaml
  config/crd/ingress-controller/configuration.konghq.com_kongclusterplugins.yaml
  config/crd/ingress-controller/configuration.konghq.com_kongconsumergroups.yaml
  config/crd/ingress-controller/configuration.konghq.com_kongconsumers.yaml
  config/crd/ingress-controller/configuration.konghq.com_kongcustomentities.yaml
  config/crd/ingress-controller/configuration.konghq.com_kongingresses.yaml
  config/crd/ingress-controller/configuration.konghq.com_konglicenses.yaml
  config/crd/ingress-controller/configuration.konghq.com_kongplugins.yaml
  config/crd/ingress-controller/configuration.konghq.com_kongupstreampolicies.yaml
  config/crd/ingress-controller/configuration.konghq.com_kongvaults.yaml
  config/crd/ingress-controller/configuration.konghq.com_tcpingresses.yaml
  config/crd/ingress-controller/configuration.konghq.com_udpingresses.yaml
Labels: area/configuration

#236 feat: add KongPluginBinding scope
  CHANGELOG.md
  api/configuration/v1alpha1/kongpluginbinding_types.go
  api/configuration/v1alpha1/zz_generated.deepcopy.go
  config/crd/gateway-operator/configuration.konghq.com_kongpluginbindings.yaml
  docs/api-reference.md
  test/crdsvalidation/kongpluginbindings_test.go
Labels: area/configuration

#239 chore(ci): add codeql code scanning
  .github/workflows/codeql.yaml
Labels: area/ci

#240 chore(ci): pin actions and ensure they are pinned
  .github/workflows/release_on_version_change.yaml
  .github/workflows/tests.yaml
Labels: area/ci

#238 fix: make KongPluginBinding's spec.controlPlaneRef required
  CHANGELOG.md
  VERSION
  api/configuration/v1alpha1/kongpluginbinding_types.go
  api/configuration/v1alpha1/zz_generated.deepcopy.go
  api/configuration/v1alpha1/zz_generated_funcs.go
  config/crd/gateway-operator/configuration.konghq.com_kongcacertificates.yaml
  config/crd/gateway-operator/configuration.konghq.com_kongcertificates.yaml
  config/crd/gateway-operator/configuration.konghq.com_kongconsumergroups.yaml
  config/crd/gateway-operator/configuration.konghq.com_kongconsumers.yaml
  config/crd/gateway-operator/configuration.konghq.com_kongcredentialacls.yaml
  config/crd/gateway-operator/configuration.konghq.com_kongcredentialapikeys.yaml
  config/crd/gateway-operator/configuration.konghq.com_kongcredentialbasicauths.yaml
  config/crd/gateway-operator/configuration.konghq.com_kongcredentialhmacs.yaml
  config/crd/gateway-operator/configuration.konghq.com_kongcredentialjwts.yaml
  config/crd/gateway-operator/configuration.konghq.com_kongdataplaneclientcertificates.yaml
  config/crd/gateway-operator/configuration.konghq.com_kongkeys.yaml
  config/crd/gateway-operator/configuration.konghq.com_kongkeysets.yaml
  config/crd/gateway-operator/configuration.konghq.com_konglicenses.yaml
  config/crd/gateway-operator/configuration.konghq.com_kongpluginbindings.yaml
  config/crd/gateway-operator/configuration.konghq.com_kongplugins.yaml
  config/crd/gateway-operator/configuration.konghq.com_kongroutes.yaml
  config/crd/gateway-operator/configuration.konghq.com_kongservices.yaml
  config/crd/gateway-operator/configuration.konghq.com_kongsnis.yaml
  config/crd/gateway-operator/configuration.konghq.com_kongtargets.yaml
  config/crd/gateway-operator/configuration.konghq.com_kongupstreams.yaml
  config/crd/gateway-operator/configuration.konghq.com_kongvaults.yaml
  config/crd/gateway-operator/konnect.konghq.com_konnectapiauthconfigurations.yaml
  config/crd/gateway-operator/konnect.konghq.com_konnectgatewaycontrolplanes.yaml
  config/crd/ingress-controller-incubator/incubator.ingress-controller.konghq.com_kongservicefacades.yaml
  config/crd/ingress-controller/configuration.konghq.com_ingressclassparameterses.yaml
  config/crd/ingress-controller/configuration.konghq.com_kongclusterplugins.yaml
  config/crd/ingress-controller/configuration.konghq.com_kongconsumergroups.yaml
  config/crd/ingress-controller/configuration.konghq.com_kongconsumers.yaml
  config/crd/ingress-controller/configuration.konghq.com_kongcustomentities.yaml
  config/crd/ingress-controller/configuration.konghq.com_kongingresses.yaml
  config/crd/ingress-controller/configuration.konghq.com_konglicenses.yaml
  config/crd/ingress-controller/configuration.konghq.com_kongplugins.yaml
  config/crd/ingress-controller/configuration.konghq.com_kongupstreampolicies.yaml
  config/crd/ingress-controller/configuration.konghq.com_kongvaults.yaml
  config/crd/ingress-controller/configuration.konghq.com_tcpingresses.yaml
  config/crd/ingress-controller/configuration.konghq.com_udpingresses.yaml
  config/samples/kongpluginbinding.yaml
  scripts/apitypes-funcs/main.go
  scripts/apitypes-funcs/supportedtypes.go
  scripts/apitypes-funcs/templates.go
  test/crdsvalidation/kongpluginbindings_test.go
  test/crdsvalidation/suite_crd_ref_change_test.go
Labels: area/configuration

#248 chore: Fix comments on KongServiceSpec
  api/configuration/v1alpha1/kongservice_types.go
  config/crd/gateway-operator/configuration.konghq.com_kongservices.yaml
  docs/api-reference.md
Labels: documentation, area/konnect

#252 chore(ci): add tests running on CI for release branches, limit permissions of GITHUB_TOKEN
  .github/workflows/release.yaml
  .github/workflows/tests.yaml
Labels: area/ci
